YEAR = 2026
ESPN_LEAGUE_ID = 290350916
MY_TEAM = "Big Baller Brand (BBb)"
MY_ESPN_S2 = "RXJaoLpmI83Wn6hE1I8CUIIJfQu6Y2DJfVXjun1nY1poVnDUAm45SJxPEGykOTSkgyBLjXvEwkyhmSiYvfxd8BedDHKHtnChl7JYkr0xE9ArNZocuNWLhSOdbizNU0tZKEGKI4vfrpy2y8eiEv4cNOVymUvEO7sGtKnwtTPLnoGUbdIiye4VKTEzx9PAXnJIWGIOdGhnozaqs9jOwuEriK3DMwMuit391tJmnlqQp0yrqVoxwfNAEgG2xFNAF1EJn2Qwq9PlwThxiRCkET2zW34i7Mc6bZT2eq9oAbNkmiUzUB0JplhuHhcu3ed6G1zO%uJhIOHQd7IlDGRP6wFCEHpXBnqnPH"
MY_SWID = "{0007e2e0-a86e-460b-8109-102b11ebb0c3}"

LOAD_FROM_CACHE = False
CACHE_HEADER_PLAYER = "Player"

ESPN_PROJECTIONS_KEY = str(YEAR) + "_projected"
ESPN_TOTAL_KEY = str(YEAR) + "_total"
ESPN_LAST_7_KEY = str(YEAR) + "_last_7"
ESPN_STATS_KEY = ESPN_PROJECTIONS_KEY
ESPN_STATS_TOTAL_KEY = "total"

ALL_STATS = ["FGM", "FGA", "FTM", "FTA", "3PM", "REB", "AST", "STL", "BLK", "TO", "PTS"]
NINE_CATEGORIES = ["FG%", "FT%", "3PM", "REB", "AST", "STL", "BLK", "TO", "PTS"]

KEY_IR = "On IR"
KEY_ROSTER = "roster"
KEY_SCHEDULE = "schedule"
KEY_STATS = "stats"
KEY_WINS = "wins"
KEY_LOSSES = "losses"
KEY_TIES = "ties"
