ESPN_LEAGUE_ID = 1192749948
YEAR = 2025
ALL_STATS = ["FGM", "FGA", "FTM", "FTA", "3PM", "REB", "AST", "STL", "BLK", "TO", "PTS"]

LOAD_FROM_CACHE = False
CACHE_HEADER_PLAYER = "Player"

ESPN_PROJECTIONS_KEY = str(YEAR) + "_projected"
ESPN_TOTAL_KEY = str(YEAR) + "_total"
ESPN_LAST_7_KEY = str(YEAR) + "_last_7"
ESPN_STATS_KEY = ESPN_PROJECTIONS_KEY
ESPN_STATS_TOTAL_KEY = "total"

ALL_STATS = ["FGM", "FGA", "FTM", "FTA", "3PM", "REB", "AST", "STL", "BLK", "TO", "PTS"]

KEY_IR = "On IR"
KEY_ROSTER = "roster"
KEY_SCHEDULE = "schedule"
