name: Python package

on: [push]

env:
  PYTHON_VERSION: "3.10"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: run basic script
        run: |
          python -m unittest -v
